# Generated by Django 5.2.8 on 2025-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('NEW', 'To Put Away'), ('TO_WATCH', 'To Watch'), ('WATCHED', 'Watched')], default='NEW', max_length=20),
        ),
    ]
